name: CI

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - 'manga_translator/**'
      - 'test/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - 'manga_translator/**'
      - 'test/**'
      - 'pyproject.toml'
      - 'poetry.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: [1.6.1]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry ${{ matrix.poetry-version }}
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: |
        poetry install --only main,test
        
    - name: Lint *.py files
      run: |
        poetry run pylint $(git ls-files '*.py')
    # - name: Test
    #   run: |
    #     poetry run pytest test